### ISSUE TITLE
empty text breaking the app

### ISSUE THREAD

**Issue by Abhishek201999** [utkarshgupta2504/todoey#2]

**Comment by utkarshgupta2504** [comment]
Please elaborate the issue so that it can be looked into.

What is breaking exactly?

**Comment by Abhishek201999** [comment]
if user press add button without entering the text it displays error message on a screen that a non-null string is provided to a text widget
![Screenshot (62)](https://user-images.githubusercontent.com/57562032/89423928-be690600-d754-11ea-8367-cc1c897c6445.png)

**Comment by utkarshgupta2504** [comment]
> if user press add button without entering the text it displays error message on a screen that a non-null string is provided to a text widget
> ![Screenshot (62)](https://user-images.githubusercontent.com/57562032/89423928-be690600-d754-11ea-8367-cc1c897c6445.png)
> 

Thank you for pointing out, I will rectify this.

**Comment by utkarshgupta2504** [comment]
This issue has been resolved in the v 1.7.4

Hence closing this issue
